### ISSUE TITLE
vertical scroll with ScrollView

### ISSUE THREAD

**Issue by kolandrey** [evrencoskun/TableView#104]
Doesn't work vertical scroll if layout contains ScrollView. If exist some solutions could you tell me please?

**Comment by evrencoskun** [comment]
Hi @kolandrey 

The problem is not about the TableView, This is about the behaviour of the RecyclerView. 

use NestedScrollView instead of ScrollView

Please go through [NestedScrollView ](https://developer.android.com/reference/android/support/v4/widget/NestedScrollView.html)reference document for more information.

**Comment by kolandrey** [comment]
I tried to use NesstedScrollView but result is the same.
Any other suggestions? )
