### ISSUE TITLE
Pinch zoom in TableView

### ISSUE THREAD

**Issue by Walpurisnacht** [evrencoskun/TableView#108]
Hello, thanks for your great library

I wonder if on small resolution device could we use pinch zoom to freely enlarge/shrink the table?
If your library can auto scale width/height by font size then maybe apply pinch zoom operation on font size changing event will help?

Thanks in advance

**Comment by evrencoskun** [comment]
Hi @Walpurisnacht ,

Unfortunately, TableView has no feature like this.  But, I have written your request.

**Comment by Zardozz** [comment]
Really this should be closed for the following reasons

- TableView can display any Android widget inside the cell, therefore just thinking about font size is a non starter
- It is pretty much impossible to do in any useful manner because all items would need to be remeasured, so it would take nearly the same amount of time as display the TableView for the first time. So it would not be responsive to pinch zooming (it might be usable to do at pinch end or via buttons) but still it would take a long time
- Your Class TableViewAdapter would have to handle how scale each widget it contained making it more complicated.

The best that could be implemented inside TableView can already be achieve without any changes to TableView, the parent view would handle detect the pinch zoom end or zoom button clicks, you would then create a new TableViewAdapter instance that lays out all the widgets at an appropriate size and then the parent view would remove the child TableView and create a new TableView using the new Adapter instance.

As a note for most things that respond to pinch zooming just draw whatever they are displaying completely to a canvas that is much larger than the display area and then displays a viewport of the display area size from the much larger canvas, then zooming is done by basic hardware accelerated bitmap scaling.
Unfortunately a recyclerview is more efficient and only draws what it need to fill it's display area

**Comment by Zardozz** [comment]
Shameless plug for https://github.com/Zardozz/FixedHeaderTableLayout/ that does similar things to TableView in fixing Table Headers BUT does support Pinch Zooming as it does not use Recycler View, instead it draws the complete table allowing it to be zoomed.

**Comment by Zardozz** [comment]
I did try implementing pinch zoom in TableView first before doing this library but ran in to the problem that because recycler views only draw what is needed then there was nothing to zoom to.

**Comment by evrencoskun** [comment]
yes makes sense.
