### ISSUE TITLE
problem with row columns when sorting

### ISSUE THREAD

**Issue by farzadkamali20** [evrencoskun/TableView#128]
hi friends
There is a bug in sorting each column of the table.
the row column must be fixed and always show the number of row table and not change with sorting each column.
for example, when sorting the name column, the row column will be changed with name column.

example:

row   name
1       james
2       danny
3       jon
4       tom

after name column sorting:

row    name
2        danny
1        james
3        jon
4        tom

the row column should not be changed after sorting.

the right to left table is support? or not yet?

**Comment by farzadkamali20** [comment]
i found it.
must call notifyCellDataSetChanged after sort.
mTableView.getAdapter().getCellRecyclerViewAdapter().notifyCellDataSetChanged();

tanks.

**Comment by evrencoskun** [comment]
Hi @farzadkamali20 

The TableView does not know what data of the Row header corresponds to. That's why adapter wants the list. 

For example, What if your TableView would like this;
![24 0_7-bootstrap-table-checkbox](https://user-images.githubusercontent.com/4228262/40907522-cf28a54c-67ec-11e8-974d-eb7117f9615f.jpg)
; 

For that case, TableView should update each of row header. 


I know, it's ugly but, you need to renew your row header list to your case.
 
In the future, there will be another adapter that doesn't need any row header list, in this way, TableView handle each of operations by itself.

**Comment by farzadkamali20** [comment]
thanks.
