### ISSUE TITLE
Select a row by default

### ISSUE THREAD

**Issue by SunshineXyq** [evrencoskun/TableView#274]
Thanks for your library！
When loading data, a row is selected by default。
For example, Load 10 rows of data, the first row is set to the selected state and the other unselected state.
How to do it？

**Comment by MGaetan89** [comment]
Seems like the same question as #269

**Comment by SunshineXyq** [comment]
I use tableview.setSelectedRow with error.
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.evrencoskun.tableview.adapter.recyclerview.holder.AbstractViewHolder.setBackgroundColor(int)' on a null object reference
I do not want to use in onCellClicked method.
I want to set the color of a certain row when loading data.

**Comment by evrencoskun** [comment]
Hi @SunshineXyq 

You are getting the error because, `setSelectedRow ` function sets a background color on a  related viewholder. However, for your case, there is no any viewholder yet. 

To achieve without handling viewHolders, you can set selected row position like this. 

`tableView.getSelectionHandler().setSelectedRowPosition(row)`
