### ISSUE TITLE
cells filling

### ISSUE THREAD

**Issue by SergArtk** [evrencoskun/TableView#277]
In adapter for cell we need to give data with this structure: List1<List2<Cell>> mCellList
TableView filling data in next order:
List1 - it is rows
List2 - it is list for each row. And rows filling in horizontal way
It is possible to change direction?
For example:
List1- it is columns 
and List2 - it is list for each column. And fill data in vertical way

Any ideas?
Thank you!

**Comment by evrencoskun** [comment]
Hi @SergArtk, 
The reason why TableView needs data like this way is because of its structure which includes nested horizontal Recyclerviews. Please check the below image out.

![structurecrop](https://user-images.githubusercontent.com/4228262/72175484-28464a80-33d4-11ea-9a4e-58d6db206ddf.png)

Therefore, you need to organize your data as TableView wants.

**Comment by SergArtk** [comment]
Thank you!
