### ISSUE TITLE
Best way to implement Row Toggle Visibility

### ISSUE THREAD

**Issue by sidharthshah** [evrencoskun/TableView#7]
Hello, 

Firstly let me thank you for putting together this lovely example. I've been trying a lot of options with lot of different approaches none of them work as smooth as your approach. 

Once extension to current example is I wanted to be able toggle visibility of the rows. What would be the best way of doing it. One solution I've thought about is is modifying "TableViewAdapter" to have a hashmap of `hiddenRows` which is a lookup of Integer {corresponding to row indicies}. And then use `setVisibility` on respective sections of `onBindCellViewHolder` and `onBindRowHeaderViewHolder`. This works at theoretical level, but it chunks/truncates random row headers. Can you suggest what would be the approach you'd take on this one?

Thank you once again.

**Comment by evrencoskun** [comment]
Hi Sidharth, 

Thank you for your kind words. 

To clarify what you want, as far as I could understand from _' toggle visibility of the rows '_ , you wants to hide & show a specific row of the TableView on runtime ( maybe by user interaction ) .  

Am I right ? 

There is two ways that help your needs. 

1. Changing the adapter model  of the TableView by removing or adding items. 
2. Hide & show the relevant viewholders. 

Unfortunately I have a bad news for you. Both of ways need some modification that you can't access to change it. However, I have also good news to you. 0.8.5 version will be published on this weekend. And I will try to add this feature to this version.

> it chunks/truncates random row headers
The reason is every item of the TableView is a RecyclerView.ViewHolder to be able to reuse views efficiently instead of needing to hold things in memory when they're not visible. The solution of that is pretty easy. But you have to wait for the new version.

**Comment by evrencoskun** [comment]
Hi Sidharth,

Even if I haven't published 0.8.5 version yet, Some new helper methods which are about your request have been inserted. 

When I implement this feature, I considered both of way that I mention above. And In my opinion, I have done with best approach. 

You can simple use these methods without mapping the keys.

1. `showRow(int row) `
2. `hideRow(int row) `
3. `showAllHiddenRows()`
4. `clearHiddenRowList()`


The new version will probably be released at the latest at the weekend. So you can test it.

Have a nice day.

**Comment by sidharthshah** [comment]
Sorry for delayed response {was enjoying holidays}, appreciate your quick response. Thank you once again!

**Comment by evrencoskun** [comment]
You're welcome Sidharth,

Have you tested the feature ?

**Comment by sidharthshah** [comment]
@evrencoskun Yes I am updating the version in gradle and checking, let me update you once I am done playing. FYI I am trying to deal with data that is 200x200 about 40,000 elements. And your library works like a charm on even the crapiest of the phones that I am testing on so hats off! {To all your hardwork and effort}

**Comment by evrencoskun** [comment]
Hehehe :) glad to hear that :)

**Comment by immosk** [comment]
I like to know, How if I want hide more rows in all at once? Let say I want to hide 100 rows?

**Comment by nikitoSha** [comment]
Hi. I cannot normaly hide a lot of rows.
Always "java.lang.IndexOutOfBoundsException: Index: 4, Size: 3". So, as I understand, hidding = removing (from recyclerView?).
Actualy, this code not working:

	for (int i=0; i<mCellList.size();i++) {
		if (mCellList.get(i).get(0).getRowLevel() > 0){
			table_.hideRow(i);
		}
	}

And this:

	for (List<CellReport2> childRow : mCellList){
		if (childRow.get(0).getRowLevel() > 0){
			table_.hideRow(mCellList.indexOf(childRow));
		}
	}

So, ho can I hide a few rows in cycle without dancing with a tambourine?

**Comment by nikitoSha** [comment]
Resolve this problem without using hide/show methods. Just delete and append rows.
