### ISSUE TITLE
changeCellItem make recyclerview scroll to start point

### ISSUE THREAD

**Issue by qwertosu** [evrencoskun/TableView#75]
When changeCellItem called in adapter, it makes the recyclerview of the cells scroll to the start point.
I think the problem is in notifyItemChanged(position) inside of mCellRecyclerViewAdapter.changeItem(rowPosition, cellItems) 
if i change the cells directly from the list and make  a call to adapter.notifyDataSetChanged() the issue is fixed.
so i think instead of notifyItemChanged(position) in mCellRecyclerViewAdapter.changeItem(rowPosition, cellItems) it should be notifyDataSetChanged

**Comment by evrencoskun** [comment]
Oh! Thanks, I 'll check this out.

**Comment by evrencoskun** [comment]
Hi @qwertosu,

I have just tested your case. However, It doesn't scroll to the start point like yours. 

Which version do you get this bug? 

In the below sample, It doesn't make to change the scroll position. However,  as you can see, it has a different bug. 

![changeditembug](https://user-images.githubusercontent.com/4228262/38466441-bbd965f4-3b31-11e8-84b1-a88f5e9b894b.gif)

It's because, others that located in the same column position, don't know that someone is changed. 
However, The solution is very simple. 

You can remeasure the related column like this;

``` java 
                  
                    mTableView.getAdapter().changeCellItem(columnPosition, 2,  myCell);

                Handler handler = new Handler();
                handler.post(new Runnable() {
                    @Override
                    public void run() {
                         // Fix the bug
                          mTableView.remeasureColumnWidth(column);
                    }
                });

```
![changecellitemfix](https://user-images.githubusercontent.com/4228262/38466466-3390d9f6-3b32-11e8-9637-cac951af03e0.gif)

On the other hand, your solution is also to fix the issue as well by notifying each cell items.


Thanks for the feedback.

**Comment by qwertosu** [comment]
Thanks for your reply, i noticed that to and fixed that before, but the bug i'm talking about happens when i change cell item itself (not in header), and when i scroll right. 
try to scroll right and change any cell item (not in header) 
and i'm using 0.8.6 version

**Comment by qwertosu** [comment]
![bug](https://user-images.githubusercontent.com/4719201/38468106-2edd3806-3b4a-11e8-9709-83b4a38c3c3c.gif)

**Comment by qwertosu** [comment]
This happens when i do 
 adapter.changeCellItem(tableCellPosition.col,tableCellPosition.row,cellItem)
but if i change it to 
tableDataHolder.cellData[tableCellPosition.row][tableCellPosition.col].data = cellItem.data
adapter.notifyDataSetChanged()
(while the tableHolderData have direct reference to cell list position)
it works

**Comment by azisoli** [comment]
when i change the cell_textview background in  onBindCellViewHolder in my adapter ,i have the same problem .what should i do ?
i need to change the background in some specific rows and columns.
thanks

**Comment by evrencoskun** [comment]
Hi @qwertosu,
Doesn't sound related, please feel free to open another issue with code
sample and I can look into it.
